  SELECT 
    OBJECT_TYPE
    ,OBJECT_SCHEMA
  	,OBJECT_NAME
  FROM (
  	SELECT 'TABLE' AS OBJECT_TYPE
  		,TABLE_NAME AS OBJECT_NAME
  		,TABLE_SCHEMA AS OBJECT_SCHEMA
  	FROM information_schema.TABLES
  	WHERE TABLE_TYPE = 'BASE TABLE'
  	UNION
  	
  	SELECT 'VIEW' AS OBJECT_TYPE
  		,TABLE_NAME AS OBJECT_NAME
  		,TABLE_SCHEMA AS OBJECT_SCHEMA
  	FROM information_schema.VIEWS
  	
  	UNION
  	
  	SELECT 'INDEX' AS OBJECT_TYPE
  		,CONSTRAINT_NAME AS OBJECT_NAME
  		,TABLE_SCHEMA AS OBJECT_SCHEMA
  	FROM information_schema.TABLE_CONSTRAINTS
  	
  	UNION
  	
  	SELECT ROUTINE_TYPE AS OBJECT_TYPE
  		,ROUTINE_NAME AS OBJECT_NAME
  		,ROUTINE_SCHEMA AS OBJECT_SCHEMA
  	FROM information_schema.ROUTINES
  	
  	UNION
  	
  	SELECT 'TRIGGER' AS OBJECT_TYPE
  		,TRIGGER_NAME AS OBJECT_NAME
  		,TRIGGER_SCHEMA AS OBJECT_SCHEMA
  	FROM information_schema.triggers
  	) R
  
  order by 1;	